# Generated by Django 5.2.2 on 2025-06-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='inv_number',
            field=models.CharField(default=3456, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
