# Generated by Django 5.2.2 on 2025-06-08 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_maintenance_cost_maintenance_performed_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='performed_by',
        ),
    ]
