# Generated by Django 5.2.2 on 2025-06-08 13:52

import django.db.models.deletion
import fernet_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_rename_date_maintenance_date_signing_contract_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hostname', models.CharField(blank=True, max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', fernet_fields.fields.EncryptedCharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('last_changed', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Documentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('doc_type', models.CharField(choices=[('CONFIG', 'Konfiguracija'), ('PROCEDURE', 'Procedura'), ('MANUAL', 'Uputstvo'), ('ARCH', 'Arhitektura/shema'), ('OTHER', 'Ostalo')], max_length=20)),
                ('upload', models.FileField(upload_to='documentation/')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.device')),
                ('related_software', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.software')),
            ],
        ),
    ]
