# Generated by Django 5.2.2 on 2025-06-08 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_credential_documentation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ITUser',
            new_name='User',
        ),
    ]
